AWSTemplateFormatVersion: "2010-09-09"
Description: "Create an IAM user with console and programmatic access"

Parameters:
  UserName:
    Type: String
    Default: dev-user
    Description: "IAM user name to create"

  UserPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: "Initial console password for the IAM user"

Resources:
  User:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName
      LoginProfile:
        Password: !Ref UserPassword
        PasswordResetRequired: true
      Policies:
        - PolicyName: S3ReadAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                Resource: "*"

  UserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref User

  UserSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${UserName}-AccessKeySecret"
      Description: "Access key and secret for IAM user ${UserName}"
      SecretString: !Sub |
        {
          "AccessKeyId": "${UserAccessKey}",
          "SecretAccessKey": "${UserAccessKey.SecretAccessKey}"
        }

Outputs:
  ConsoleLoginUrl:
    Description: "AWS console sign-in URL"
    Value: !Sub "https://console.aws.amazon.com/"

  AccessKeyId:
    Description: "Access key ID for programmatic access (SecretAccessKey is stored in Secrets Manager)"
    Value: !Ref UserAccessKey
